

function fnBrand() {
  new TypeIt(".brand", {
    lifeLike: false,
    speed: 0
  })
    /*  .type("S")
    .pause(80)
    .type("t")
    .pause(80)
    .type("ü")
    .pause(80)
    .type("s")
    .pause(80)
    .type("s")
    .pause(80)
    .type("y")
    .pause(80)
    .type(" ")
    .pause(80)
    .type("X")
    .pause(80) */ 
    .type(" ")
    .pause(80)
    .type("B")
    .pause(80)
    .type("r")
    .pause(80)
    .type("a")
    .pause(80)
    .type("n")
    .pause(80)
    .type("d")
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .type("C")
    .pause(80)
    .type("O")
    .pause(80)
    .type("L")
    .pause(80)
    .type("L")
    .pause(80)
    .type("A")
    .pause(80)
    .type("B")
    .pause(80)
    .type("O")
    .pause(80)
    .type("R")
    .pause(80)
    .type("A")
    .pause(80)
    .type("T")
    .pause(80)
    .type("I")
    .pause(80)
    .type("O")
    .pause(80)
    .type("N")
    .go();
}

function fnNike() {
  new TypeIt(".Nike", {
    lifeLike: false,
    speed: 0
  })
   /*  .type("S")
    .pause(80)
    .type("t")
    .pause(80)
    .type("ü")
    .pause(80)
    .type("s")
    .pause(80)
    .type("s")
    .pause(80)
    .type("y")
    .pause(80)
    .type(" ")
    .pause(80)
    .type("X")
    .pause(80)*/
    .type(" ")
    .pause(80)
    .type("B")
    .pause(80)
    .type("r")
    .pause(80)
    .type("a")
    .pause(80)
    .type("n")
    .pause(80)
    .type("d")
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .type("N")
    .pause(80)
    .type("I")
    .pause(80)
    .type("K")
    .pause(80)
    .type("E")
    .go();
}

function fnTim() {
  new TypeIt(".Tim", {
    lifeLike: false,
    speed: 0
  })
  /*   .type("S")
    .pause(80)
    .type("t")
    .pause(80)
    .type("ü")
    .pause(80)
    .type("s")
    .pause(80)
    .type("s")
    .pause(80)
    .type("y")
    .pause(80)
    .type(" ")
    .pause(80)
    .type("X")
    .pause(80)*/
    .type(" ")
    .pause(80)
    .type("B")
    .pause(80)
    .type("r")
    .pause(80)
    .type("a")
    .pause(80)
    .type("n")
    .pause(80)
    .type("d")
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .type("T")
    .pause(80)
    .type("i")
    .pause(80)
    .type("m")
    .pause(80)
    .type("b")
    .pause(80)
    .type("e")
    .pause(80)
    .type("r")
    .pause(80)
    .type("l")
    .pause(80)
    .type("a")
    .pause(80)
    .type("n")
    .pause(80)
    .type("d")
    .go();
}

function fnDr() {
  new TypeIt(".Dr", {
    lifeLike: false,
    speed: 0
  })
   /*  .type("S")
    .pause(80)
    .type("t")
    .pause(80)
    .type("ü")
    .pause(80)
    .type("s")
    .pause(80)
    .type("s")
    .pause(80)
    .type("y")
    .pause(80)
    .type(" ")
    .pause(80)
    .type("X")
    .pause(80) 
    .type(" ")
    .pause(80)*/ 
    .type(" ")
    .pause(80)
    .type("B")
    .pause(80)
    .type("r")
    .pause(80)
    .type("a")
    .pause(80)
    .type("n")
    .pause(80)
    .type("d")
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .type("D")
    .pause(80)
    .type("R")
    .pause(80)
    .type(".")
    .pause(80)
    .type("M")
    .pause(80)
    .type("a")
    .pause(80)
    .type("r")
    .pause(80)
    .type("t")
    .pause(80)
    .type("e")
    .pause(80)
    .type("n")
    .pause(80)
    .type("s")
    .go();
}

function fnHolden() {
  new TypeIt(".Holden", {
    lifeLike: false,
    speed: 0
  })
   /*  .type("S")
    .pause(80)
    .type("t")
    .pause(80)
    .type("ü")
    .pause(80)
    .type("s")
    .pause(80)
    .type("s")
    .pause(80)
    .type("y")
    .pause(80)
    .type(" ")
    .pause(80)
    .type("X")
    .pause(80) 
    .type(" ")
    .pause(80)*/
    .type(" ")
    .pause(80)
    .type("B")
    .pause(80)
    .type("r")
    .pause(80)
    .type("a")
    .pause(80)
    .type("n")
    .pause(80)
    .type("d")
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .type("H")
    .pause(80)
    .type("O")
    .pause(80)
    .type("L")
    .pause(80)
    .type("D")
    .pause(80)
    .type("E")
    .pause(80)
    .type("N")
    .go();
}

function fnGivanchy() {
  new TypeIt(".Givanchy", {
    lifeLike: false,
    speed: 0
  })
    /*  .type("S")
    .pause(80)
    .type("t")
    .pause(80)
    .type("ü")
    .pause(80)
    .type("s")
    .pause(80)
    .type("s")
    .pause(80)
    .type("y")
    .pause(80)
    .type(" ")
    .pause(80)
    .type("X")
    .pause(80) 
    .type(" ")
    .pause(80)*/ 
    .type(" ")
    .pause(80)
    .type("B")
    .pause(80)
    .type("r")
    .pause(80)
    .type("a")
    .pause(80)
    .type("n")
    .pause(80)
    .type("d")
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .delete(1)
    .pause(80)
    .type("G")
    .pause(80)
    .type("I")
    .pause(80)
    .type("V")
    .pause(80)
    .type("A")
    .pause(80)
    .type("N")
    .pause(80)
    .type("C")
    .pause(80)
    .type("H")
    .pause(80)
    .type("Y")
    .go();
}